# 1. Dirección de la base de datos
# Esto creará un archivo llamado 'cotizaciones.db' en la carpeta raíz de tu proyecto
spring.datasource.url=jdbc:sqlite:pricing.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Dialecto de Hibernate
# Necesario para que Hibernate sepa cómo "hablar" en el lenguaje de SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 3. Estrategia de creación de tablas
# 'update' hará que Spring cree las tablas automáticamente basándose en tus clases @Entity
# Si cambias algo en la clase Java, la tabla se actualiza sola al reiniciar
spring.jpa.hibernate.ddl-auto=update

# 4. Logs (Opcional pero muy útil)
# Muestra en la consola de IntelliJ las consultas SQL que Spring hace por ti
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
